### ISSUE TITLE
Unable to find manifests/train.csv

### ISSUE THREAD

**Issue by TFM-HITESH** [xi-j/Mamba-ASR#2]
I am trying to train the model on the LibriSpeech dataset. But it is unable to create the train.csv file for some reason. 

speechbrain.core - Beginning experiment!
speechbrain.core - Experiment folder: results/S2S/conmambamamba_S_S2S/7775
speechbrain.core - Exception:
Traceback (most recent call last):
  File "/mnt/Work/VSCODE/Mamba-ASR/train_S2S.py", line 425, in <module>
    ) = dataio_prepare(hparams)
  File "/mnt/Work/VSCODE/Mamba-ASR/train_S2S.py", line 257, in dataio_prepare
    train_data = sb.dataio.dataset.DynamicItemDataset.from_csv(
  File "/home/tfmhitesh/.conda/envs/Slytherin/lib/python3.9/site-packages/speechbrain/dataio/dataset.py", line 408, in from_csv
    data = load_data_csv(csv_path, replacements)
  File "/home/tfmhitesh/.conda/envs/Slytherin/lib/python3.9/site-packages/speechbrain/dataio/dataio.py", line 129, in load_data_csv
    with open(csv_path, newline="") as csvfile:
FileNotFoundError: [Errno 2] No such file or directory: 'manifests/train.csv'

Is the building of train.csv not working or is it some silly mistake that I am committing ? 

Thank you for the help !

**Comment by xi-j** [comment]
Thanks for pointing this out. 
'manifests/train.csv' is created by prepare_librispeech in librispeech_prepare.py. 
You can either run it by yourself or make the following changes in your yaml (I just updated in all yaml files).
```
skip_prep: False
train_csv: !ref <output_folder>/train.csv
valid_csv: !ref <output_folder>/dev-clean.csv
test_csv:
    - !ref <output_folder>/test-clean.csv
    - !ref <output_folder>/test-other.csv
```
If skip_prep == True, train_S2S/CTC.py will call prepare_librispeech to create manifests in your experiment folder <output_folder>. Since these manifests are same for all experiments, you can put them in one place e.g. manifests/train.csv and set skip_prep: False to save time in later runs.

**Comment by TFM-HITESH** [comment]
Thank you so much ! I am in college but will try and run the updated versions after some hours. Deeply appreciate the quick response, great project :)

**Comment by TFM-HITESH** [comment]
It is working as intended now. I am coming across another error but that is to do with my GPU setup. The project seems to be working as expected. Thanks again for the prompt response !
